In [4]:
a = 1
b = 2
c = 3
d = 4

a+b, a-b, a*c

print(a+b)
print(a-b)
print(a*c)
print(a*b)
print(d/b)
print(d%c)

3
-1
3
2
2.0
1


In [6]:
a = input()
type(a)

 10


str

In [7]:
a=123
b=-123
c=0
type(a)


int

In [9]:
a=1.2
b=-2.1
type(a)

float

In [11]:
a = 1.24e-2
a

0.0124

In [12]:
b=1.24E2
b

124.0

In [13]:
10<15


True

In [14]:
10>15

False

In [16]:
print("=" *50)
print("My Program")
print("=" *50)

My Program


In [17]:
A = [1, 2, 3, 4, 5]
type(A)

B = [1, 2, 3, 4, 5]
type(B)

TypeError: 'type' object is not subscriptable

In [19]:
a = "독고영재, 50"
b = "김철수, 30"
people = [a, b]
people

['독고영재, 50', '김철수, 30']

In [20]:
A = [10, 20, 30]
B = (10, 20, 30)
A, B

([10, 20, 30], (10, 20, 30))

In [33]:
import numpy as np

a=np.array([1,2,3])
b=np.array([5,6,7])
c=a+b
d=b+a
c.shape
print(c)
print(d)
type(c)

[ 6  8 10]
[ 6  8 10]


numpy.ndarray

In [32]:
a=[1,2,3]
b=[5,6,7]
a+b

[1, 2, 3, 5, 6, 7]

In [42]:
D = [1,2,4,"a"]
E = np.array(D)

print(D)
print(E)
D*2

[1, 2, 4, 'a']
['1' '2' '4' 'a']


[1, 2, 4, 'a', 1, 2, 4, 'a']

In [40]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
c.shape


(2, 3)

In [41]:
a = [1,2]
a*2

[1, 2, 1, 2]

In [46]:
a = [1,5,7,8,10,"안녕","a"]



print(h)


print("-" * 50)
print("데이터전처리 수업")
print("끝")
print("=" * 50)

[1 2 4 5 2 3 5 6]
[21 21 21 21 21 21]
--------------------------------------------------
데이터전처리 수업
끝


In [49]:
b = [1,2,4,5]
c=[2,3,5,6]
h=np.array(b)
i=np.array(c)
j=h+i


array([ 3,  5,  9, 11])

In [52]:
d=np.array([[1,2,3,4,5,6], [20,19,18,17,16,15]])
d



array([[ 1,  2,  3,  4,  5,  6],
       [20, 19, 18, 17, 16, 15]])