In [147]:
#(4주차)

In [2]:
a = 1
b = 2
c = 3
d = 4

a+b, a-b, a*c

print(a+b)
print(a-b)
print(a*c)
print(a*b)
print(d/b)
print(d%c)

3
-1
3
2
2.0
1


In [6]:
a = input()
type(a)

 10


str

In [7]:
a=123
b=-123
c=0
type(a)


int

In [9]:
a=1.2
b=-2.1
type(a)

float

In [11]:
a = 1.24e-2
a

0.0124

In [12]:
b=1.24E2
b

124.0

In [13]:
10<15


True

In [14]:
10>15

False

In [16]:
print("=" *50)
print("My Program")
print("=" *50)

My Program


In [1]:
A = [1, 2, 3, 4, 5]
type(A)

B = [1, 2, 3, 4, 5]
type(B)

list

In [19]:
a = "독고영재, 50"
b = "김철수, 30"
people = [a, b]
people

['독고영재, 50', '김철수, 30']

In [20]:
A = [10, 20, 30]
B = (10, 20, 30)
A, B

([10, 20, 30], (10, 20, 30))

In [33]:
import numpy as np

a=np.array([1,2,3])
b=np.array([5,6,7])
c=a+b
d=b+a
c.shape
print(c)
print(d)
type(c)

[ 6  8 10]
[ 6  8 10]


numpy.ndarray

In [32]:
a=[1,2,3]
b=[5,6,7]
a+b

[1, 2, 3, 5, 6, 7]

In [42]:
D = [1,2,4,"a"]
E = np.array(D)

print(D)
print(E)
D*2

[1, 2, 4, 'a']
['1' '2' '4' 'a']


[1, 2, 4, 'a', 1, 2, 4, 'a']

In [40]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
c.shape


(2, 3)

In [41]:
a = [1,2]
a*2

[1, 2, 1, 2]

In [46]:
a = [1,5,7,8,10,"안녕","a"]



print(h)


print("-" * 50)
print("데이터전처리 수업")
print("끝")
print("=" * 50)

[1 2 4 5 2 3 5 6]
[21 21 21 21 21 21]
--------------------------------------------------
데이터전처리 수업
끝


In [49]:
b = [1,2,4,5]
c=[2,3,5,6]
h=np.array(b)
i=np.array(c)
j=h+i


array([ 3,  5,  9, 11])

In [52]:
d=np.array([[1,2,3,4,5,6], [20,19,18,17,16,15]])
d



array([[ 1,  2,  3,  4,  5,  6],
       [20, 19, 18, 17, 16, 15]])

In [146]:
#(5주차)

In [7]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."
A[0:5]

'안녕하세요'

In [8]:
A[-5:]

'간입니다.'

In [12]:
A[-6:-4]

'시간'

In [14]:
A[21:23]

'시간'

In [17]:
print("안녕하세요\n반갑습니다")

안녕하세요
반갑습니다


In [19]:
A = "당신의 영어 성적은 {}점입니다. 그리고 수학 성적은 {}점입니다."
A.format(100,100)

'당신의 영어 성적은 100점입니다. 그리고 수학 성적은 100점입니다.'

In [23]:
print(("{:.2f},{:.3f}").format(3.1415,3.1415))

3.14,3.142


In [27]:
url = "https://www.naver.com/"
str = url.replace("https://","")
print(str)

www.naver.com/


In [33]:
A = ["독고영재, 50", "김철수,30"]
A[0][0:4]

'독고영재'

In [39]:
a="독고영재,50" 
a[:a.index(",")] 

'독고영재'

In [40]:
b="김철수,30"
b[:b.index(",")]

'김철수'

In [45]:
a = ["독고영재, 50", "김철수,30"]
b = ["김철수, 20", "김영희,25"]
a[0][:a[0].index(",")] 

'독고영재'

In [47]:
a = ["독고영재, 50", "김철수,30"]
b = ["김철수, 20", "김영희,25"]
b[1][:b[1].index(",")] 

'김영희'

In [50]:
a=["hi", 10, "80", "김철수", 50, 50.6]
type(a[1])

int

In [51]:
type(a[3])

str

In [52]:
type(a[5])

float

In [54]:
a=["hi", 10, "80", "김철수", 50, 50.6]
a.append(1)
a

['hi', 10, '80', '김철수', 50, 50.6, 1]

In [56]:
a.pop(1)
a

['hi', '김철수', 50, 50.6, 1]

In [58]:
a=["hi", 10, "80", "김철수", 50, 50.6]
a.index(50)
a.pop(4)
a

['hi', 10, '80', '김철수', 50.6]

In [63]:
a=["hi", 10, "80", "김철수", 50, 50.6]
b=a.index("80")
a.pop(b)
a

['hi', 10, '김철수', 50, 50.6]

In [120]:
import numpy as np

In [121]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [122]:
a=np.append(a,[4,5])
a

array([1, 2, 3, 4, 4, 5])

In [123]:
a=np.insert(a, 1, [7,8])
a

array([1, 7, 8, 2, 3, 4, 4, 5])

In [124]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [125]:
a=np.delete(a, [1,3])

In [126]:
a= a[a<=4]
a

array([1, 3])

In [127]:
a= a[a!=4]
a

array([1, 3])

In [128]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
merged_array = np.vstack((array1, array2))
print(merged_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [129]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
merged_array = np.hstack((array1, array2))
print(merged_array)

[[1 2 5 6]
 [3 4 7 8]]


In [130]:
A={1:"김철수", 20:"박영희"}

In [131]:
A[1]

'김철수'

In [145]:
#(오류문제)
A[2]

KeyError: 2

In [133]:
A.get(1)

'김철수'

In [134]:
A.get(3)

In [135]:
A={"1-A":"김철수", "20-B":"박영희"}

In [136]:
A["1-A"]

'김철수'

In [137]:
A["20-B"]

'박영희'

In [138]:
A.get("1-A")

'김철수'

In [139]:
A.get("20-B")

'박영희'

In [140]:
A={"1-A":"김철수", "20-B":"박영희"}
A["2-A"] = "영희"
A

{'1-A': '김철수', '20-B': '박영희', '2-A': '영희'}

In [141]:
A={
    "1-A":[1,2,3,4,5],
    "20-B":["A","B","C","D","E"]
}
A

{'1-A': [1, 2, 3, 4, 5], '20-B': ['A', 'B', 'C', 'D', 'E']}

In [144]:
#(문제)

In [190]:
#1
a = [10, 20, 30, [1,2,3]]

In [191]:
#2
print(a[3])

[1, 2, 3]


In [216]:
#3
수학점수=[20,30,40,50,60]
영어점수=[50,70,50,60,90]

In [193]:
#4
url = "https://www.youtube.com/"
str = url.replace("https://www.youtube.com/","www.naver.com")
print(str)

www.naver.com


In [215]:
#5
수학점수 = [20,30,40,50,60]
영어점수 = [50,70,50,60,90]

수학점수_평균 = sum(수학점수)/len(수학점수)
영어점수_평균 = sum(영어점수)/len(영어점수)

print("수학평균:", 수학점수_평균)
print("영어평균:", 영어점수_평균)

수학평균: 40.0
영어평균: 64.0


In [212]:
#6
a = [1,2,100,4,5,900]
a.pop(2)
a.pop(-1)
a

[1, 2, 4, 5]

In [218]:
#7
A={"수학점수" : [20, 30, 40, 50, 60], "영어점수" : [50, 70, 50 , 60, 90]}

In [214]:
#8
A["수학점수"][0] + A["영어점수"][2]

70